<div class="jumbotron">
    <h1>Bem vindo <span class="zf-green">Zend Framework</span></h1>

   
</div>




<div class="jumbotron">
    <h3>Lista de certificados</h3>

     <div id="list" class="row">
 
    <div class="table-responsive col-md-12">
        <table class="table table-striped" cellspacing="0" cellpadding="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    
                    <th class="actions">Ações</th>
                 </tr>
            </thead>
            <tbody>
 
                <tr>
                    <td>1001</td>
                    <td>Certificado de fulano</td>
                    
                    <td class="actions">
                        <a class="btn btn-success btn-xs" href="#">Detalhes</a>
                        
                    </td>
                </tr>
 
            </tbody>
            <tbody>
 
                <tr>
                    <td>1002</td>
                    <td>Certificado do ciclano</td>
                    
                    <td class="actions">
                        <a class="btn btn-success btn-xs" href="#">Detalhes</a>
                        
                    </td>
                </tr>
 
            </tbody>
         </table>
 
     </div>
 </div> <!-- /#list -->

</div>

<div class="jumbotron">
    <h3>Envio de certificados</h3>


    <form action="#" method="post" id="form">
        <fieldset>
            <label for="nome">Nome do certificado:</label>
            <input type="text" name="nome" size="35" title="Digite o nome" id="nome"/></br>
            
            <label for="nome">Certificado(PEM):</label>
            
            <input name="arquivo" type="file"></br>
            
            <input type="submit" name="enviar" value="Enviar" />
        </fieldset>
    </form>
</div>

<div class="jumbotron">
    <div id="bottom" class="row">
    <div class="col-md-12">
         
        <ul class="pagination">
            <li class="disabled"><a>&lt; Anterior</a></li>
            <li class="disabled"><a>1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li class="next"><a href="#" rel="next">Próximo &gt;</a></li>
        </ul><!-- /.pagination -->
 
    </div>
</div> <!-- /#bottom -->
 
 <div align="center"><a href="https://github.com/cpdrenato"><img src="img/github-300x300.png" alt="git" width="33" height="33" longdesc="https://github.com/cpdrenato"></a>
      </div>
</div>

   